#version 450
#pragma kernel main

GLSLPROGRAM

layout(std430, binding = 0)buffer Result { int result2[]; };

layout(std430, binding = 1)buffer spsp { int sp[]; };

layout(local_size_x = 1, local_size_y = 1, local_size_z = 1) in;

layout(std140)uniform Globals{ int intTest; };

int func(int x) { return x + 10; }

void main()
{
	result2[0] = func(201)+sp[0]*int(gl_LocalInvocationID.x)+intTest;
}

ENDGLSL